audit_header: false
title: Epstein Financial Video Blog
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Charlie Epstein
  license_number:
  about_markdown:
  market:
  brand: Epstein Financial
  brokerage:
  address: '330 Whitney Avenue, Suite 610<br>Holyoke, MA 01040'
  phone: 413-538-2374
  phone_type: Wealth Management
  phone2: 413-539-2371
  phone2_type: Corporate 401k Management
  email:
  url: www.epsteinfinancial.com
  first_CTA_text: Home Evaluation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
  VR_form:
welcome_headline: Get Educated About Your Finacial Future
welcome_text_markdown: Our mission at Epstein Financial is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Killing-Retirement-1035473689829257'
  linkedin_url: 'https://www.linkedin.com/in/the401kcoachs'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCA-OstM4oeJwKmXaGYDnp1g'
  twitter_url: 'https://twitter.com/Charlie401K'
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title:
  categories:
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text: Epstein Finacial Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
brand_color: '#e84f41'
theme_color: '#e84f41'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'