audit_header: false
title: Epstein Financial Video Blog
description: 'We create greater clarity, confidence and the capabilities for entrepreneurs, medical practitioners, 401k participants and retirees to maximize the power of their financial future. Our goal is to help you generate a "paycheck for life" to pay for all the things you desire to do and to live a fulfilling and engaged life.'
show_custom_links: false
custom_links:
  - title:
    url:
about_tab:
  - link_name: Our Company
    link_url: https://www.epsteinfinancial.com/our-company.html
  - link_name: ADV & Disclosures
    link_url: https://www.epsteinfinancial.com/adv-disclosures.html
family_CFO_tab:
  - link_name: 6 Step Process
    link_url: https://www.epsteinfinancial.com/the-family-cfo.html
corporate_401k_tab:
  - link_name: Fiducuary Compliance & Assessement
    link_url: https://www.epsteinfinancial.com/fiduciary-compliance-assessement.html
  - link_name: Capital Market Updates
    link_url: https://www.epsteinfinancial.com/capital-market-updates.html
  - link_name: Participant Education Process
    link_url: https://www.epsteinfinancial.com/participant-education-process.html
  - link_name: Desirement Mortgage Calculator
    link_url: https://www.epsteinfinancial.com/desirement-mortgage-calculator.html
  - link_name: Newsletter
    link_url: https://www.epsteinfinancial.com/newsletter.html
  - link_name: Resources
    link_url: https://www.epsteinfinancial.com/401k-resources.html
  - link_name: Fiduciary Briefcase
    link_url: https://www.fiduciarybriefcase.com/
client:
  name: Charlie Epstein
  license_number:
  about_markdown:
  market:
  brand: Epstein Financial Services
  brokerage:
  address: '330 Whitney Avenue, Suite 610<br>Holyoke, MA 01040'
  service: <b>Marie Forest</b><br>Director of Events & Client Services
  service2:
  phone: 413-539-2371
  phone2:
  email: MForest@The401KCoach.com
  email2:
  url: www.epsteinfinancial.com
  url2:
  first_CTA_text: Get Our Free Book
  first_CTA_URL: http://saveamericasave.org/
  # second_CTA_text: Schedule a Consultation
  # second_CTA_URL: https://secure.scheduleonce.com/Consultation-EpsteinFinancial

emma_form:

welcome_headline: Get Educated About Your Financial Future
welcome_text_markdown: Our mission at Epstein Financial is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Killing-Retirement-1035473689829257'
  linkedin_url: 'https://www.linkedin.com/in/the401kcoach'
  gplus_url: https://plus.google.com/113769449383457796258
  youtube_url: 'https://www.youtube.com/channel/UCA-OstM4oeJwKmXaGYDnp1g'
  twitter_url: 'https://twitter.com/Charlie401K'
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/save-america-save-financial/id1190114230?mt=2
podcast:
  title: Save America, Save - A Financial Services Podcast with Charlie Epstein
  categories: News &amp; Politics
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more to better prepare yourself for the future.'
  description: 'We create greater clarity, confidence and the capabilities for entrepreneurs, medical practitioners, 401k participants and retirees to maximize the power of their financial future. Our goal is to help you generate a "paycheck for life" to pay for all the things you desire to do and to live a fulfilling and engaged life.'
  keywords: 'finance, epstein, financial, 401k, retirement'
  author: Charlie Epstein
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text:
  hero_background_hex: '#000000'
  hero_image_path: /img/background.jpg
brand_color: '#FDB913'
theme_color: '#000000'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
